 [2016-10-19 18:01:46,315] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
 [2016-10-19 18:01:49,537] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:01:52,016] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:01:54,729] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:01:57,726] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:00,226] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:02,947] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:05,702] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:08,252] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:10,966] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:13,681] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:16,403] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:19,115] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:21,862] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:24,570] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:27,283] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:30,027] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:32,741] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:35,440] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:38,139] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:40,892] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:43,377] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:45,848] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:48,659] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:51,370] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:54,073] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:56,787] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:02:59,486] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:02,018] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:04,556] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:07,273] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:10,036] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:12,566] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:15,268] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:18,006] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:20,745] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:23,273] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:25,980] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:28,513] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:31,224] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:33,933] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:36,656] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:39,361] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:42,064] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:44,766] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:47,476] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:50,212] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:52,728] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:55,439] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:03:58,161] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:00,632] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:03,350] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:06,074] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:08,547] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:11,263] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:13,754] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:16,491] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:19,200] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:21,916] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:24,382] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:26,864] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:29,570] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:32,279] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:04:34,989] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:30:38,095] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
 [2016-10-19 18:30:41,521] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:30:44,239] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:30:46,942] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:30:49,664] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:30:52,206] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:30:54,910] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:30:57,631] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:00,350] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:03,066] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:05,793] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:08,496] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:11,205] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:13,913] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:16,626] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:19,173] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:21,871] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:24,596] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:27,303] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:29,845] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:32,414] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:35,103] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:37,821] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:40,615] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:43,082] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:45,783] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:48,523] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:51,232] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:53,927] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:56,633] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:31:59,367] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:02,070] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:04,776] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:07,490] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:10,197] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:12,897] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:15,600] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:18,315] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:20,890] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:23,595] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:26,297] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:29,004] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:31,707] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:34,413] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:37,114] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:39,823] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:42,552] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:45,293] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:48,003] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:50,713] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:53,428] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:56,147] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:32:58,851] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:33:01,561] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:33:04,268] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:33:06,804] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:33:09,516] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:33:12,214] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:33:14,742] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:33:17,452] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:33:20,156] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:33:26,338] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:33:29,051] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:33:31,779] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:01,073] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
 [2016-10-19 18:49:04,612] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:07,337] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:10,058] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:12,778] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:15,480] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:18,184] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:20,888] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:23,607] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:26,311] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:29,024] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:31,745] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:34,456] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:37,161] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:39,871] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:42,608] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:45,327] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:48,029] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:50,737] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:53,483] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:56,181] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:49:58,896] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:01,624] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:04,416] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:07,128] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:09,827] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:12,555] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:15,262] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:17,966] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:20,665] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:23,377] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:26,092] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:28,800] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:31,522] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:34,229] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:36,948] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:39,640] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:42,351] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:45,060] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:47,777] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:50,479] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:53,187] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:55,891] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:50:58,596] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:01,304] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:04,063] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:06,806] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:09,513] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:12,238] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:14,707] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:17,418] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:19,921] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:22,651] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:25,370] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:28,070] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:30,786] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:33,251] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:35,980] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:38,686] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:41,204] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:43,919] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:46,637] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:49,360] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:51,857] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:52,302] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
 [2016-10-19 18:51:55,043] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:51:57,751] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:00,482] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:03,215] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:05,687] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:08,239] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:10,951] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:13,707] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:16,406] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:19,118] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:21,831] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:24,543] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:27,237] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:29,936] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:32,653] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:35,355] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:38,056] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:40,753] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:43,458] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:45,922] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:48,624] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:51,334] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:54,040] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:55,272] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
 [2016-10-19 18:52:56,501] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:52:59,234] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:01,733] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:04,467] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:07,182] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:09,754] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:12,447] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:15,156] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:17,876] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:20,592] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:23,293] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:26,025] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:28,709] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:31,424] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:34,155] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:36,865] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:39,552] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:42,287] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:45,008] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:47,479] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:50,203] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:52,901] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:55,625] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:53:58,338] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:01,056] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:03,786] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:06,514] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:09,238] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:12,033] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:14,774] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:17,493] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:20,225] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:27,937] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:30,652] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:33,416] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:36,121] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:38,819] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:41,567] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:44,281] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:46,999] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:49,932] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:52,636] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:54,050] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
 [2016-10-19 18:54:55,348] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:54:58,046] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:01,192] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:03,890] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:06,593] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:09,304] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:12,098] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:14,797] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:17,521] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:20,005] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:22,740] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:25,446] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:28,160] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:30,883] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:33,608] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:36,339] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:38,491] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
 [2016-10-19 18:55:39,064] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:40,428] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
 [2016-10-19 18:55:41,782] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:44,497] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:47,193] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:49,894] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:52,663] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:55,360] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:55:58,056] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:00,798] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:03,536] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:06,240] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:08,718] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:11,445] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:14,235] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:16,956] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:19,648] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:22,363] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:25,085] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:27,569] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:30,285] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:32,984] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:35,685] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:38,396] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:41,098] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:43,802] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:46,517] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:49,222] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:51,926] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:54,386] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:57,091] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:56:59,802] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:02,543] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:05,281] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:07,986] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:10,463] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:13,201] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:16,012] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:18,769] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:21,473] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:24,182] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:26,941] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:29,635] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:32,342] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:35,068] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:57:37,792] [ERROR] [boto] 400 Bad Request
 [2016-10-19 18:58:23,143] [ERROR] [django.request] Internal Server Error: /
Traceback (most recent call last):
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 86, in render_compressed
    return self.render_offline(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 71, in render_offline
    'You may need to run "python manage.py compress".' % key)
OfflineGenerationError: You have offline compression enabled but key "3034a725e0faa85e952f1e570b4b213f" is missing from offline manifest. You may need to run "python manage.py compress".
 [2016-10-19 18:59:38,335] [ERROR] [django.request] Internal Server Error: /
Traceback (most recent call last):
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 86, in render_compressed
    return self.render_offline(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 71, in render_offline
    'You may need to run "python manage.py compress".' % key)
OfflineGenerationError: You have offline compression enabled but key "3034a725e0faa85e952f1e570b4b213f" is missing from offline manifest. You may need to run "python manage.py compress".
 [2016-10-19 18:59:39,860] [ERROR] [django.request] Internal Server Error: /
Traceback (most recent call last):
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 86, in render_compressed
    return self.render_offline(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 71, in render_offline
    'You may need to run "python manage.py compress".' % key)
OfflineGenerationError: You have offline compression enabled but key "3034a725e0faa85e952f1e570b4b213f" is missing from offline manifest. You may need to run "python manage.py compress".
 [2016-10-19 19:06:33,896] [ERROR] [django.request] Internal Server Error: /
Traceback (most recent call last):
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 86, in render_compressed
    return self.render_offline(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 71, in render_offline
    'You may need to run "python manage.py compress".' % key)
OfflineGenerationError: You have offline compression enabled but key "3034a725e0faa85e952f1e570b4b213f" is missing from offline manifest. You may need to run "python manage.py compress".
 [2016-10-19 19:07:50,584] [ERROR] [django.request] Internal Server Error: /
Traceback (most recent call last):
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 99, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 78, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/cache.py", line 94, in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/base.py", line 176, in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/base.py", line 170, in mtimes
    for kind, value, basename, elem in self.split_contents()
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/css.py", line 21, in split_contents
    filename = self.get_filename(basename)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/compressor/base.py", line 138, in get_filename
    self.finders and " or with staticfiles." or "."))
UncompressableFileError: 'theme/lib/Hover/hover.css' could not be found in the COMPRESS_ROOT '/home/instanalytics/staticfiles' or with staticfiles.
 [2016-10-19 19:15:49,491] [ERROR] [django.request] Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/rith27/workspace/Poster-Analytics/authentication/views.py", line 53, in get
    return redirect(reverse("go_hireluther"))
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'go_hireluther' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
 [2016-10-19 19:17:41,474] [ERROR] [django.request] Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/rith27/workspace/Poster-Analytics/authentication/views.py", line 53, in get
    return redirect(reverse("go_hireluther"))
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'go_hireluther' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
 [2016-10-19 19:39:28,586] [ERROR] [django.request] Internal Server Error: /
Traceback (most recent call last):
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rith27/workspace/Poster-Analytics/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/rith27/workspace/Poster-Analytics/instanalysis/views.py", line 39, in get
    mapInfo, publications, hashtags = self.getMapInfo(request)
  File "/home/rith27/workspace/Poster-Analytics/instanalysis/apps/map/views.py", line 93, in getMapInfo
    start_date = datetime.strptime(request.GET.get('start_date'), "%d/%m/%Y")
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '23' does not match format '%d/%m/%Y'
